### ISSUE TITLE
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by neominky** [homov/LibMpv#10]
The unmodified sample code was changed to .NET8.
An error like this occurs about 1 in 5 times in WSL.
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory

**Comment by homov** [comment]
Unfortunately, this problem most likely relates to the operation of libmpv in WSL and possibly your configuration, so I cannot help. This project is a wrapper on libmpv and does not affect how libmpv functions in different environments.

You can ask the libmpv community for help. Although I’m not sure that they will pay attention to the problems of libmpv work in WSL.

I will be grateful if you find the cause of the problem and let me know.
