### ISSUE TITLE
Mpv detached on Windows with OpenGL

### ISSUE THREAD

**Issue by cybertron-cube** [homov/LibMpv#3]
After cloning the repo and updating the avalonia version to 11.0.0 (currently the latest release) clicking the load button spawns an mpv window instead of embedding in the avalonia application. It seems as though some breaking change (probably to OpenGlControlBase) happened between rc1.1 and rc2.2 of avalonia as rc1.1 works properly and rc2.2 has the same issue.

I would also like to say that this could be related to #2. I say this because when using the beta build *11.0.999-cibuild0036903-beta* (this was a build made from changes that the avalonia dev team committed), this issue, as well as #2 were not present.

This issue may only be present on windows (10) it seems, I tried on linux vm and this issue did not occur

**Comment by homov** [comment]
Apparently this issue has been resolved by Avalonia 11.0.999-cibuild0037413-beta
Details https://github.com/AvaloniaUI/Avalonia/pull/12056

**Comment by homov** [comment]
I've updated the avalonia beta build links. Apparently with the latest assemblies it works as it should.
