### ISSUE TITLE
Issue With "Context.Position.Seconds"

### ISSUE THREAD

**Issue by pvogt** [homov/LibMpv#5]
There seems to be an issue where "Context.Position.Seconds" resets to 0 and starts counting up again after getting to the 60 second mark of playback time.

Using your SimplePlayer.Avalonia project sample, changing the Slider xaml to:

`<Slider`
`    Grid.Column="1"`
`    IsEnabled="{Binding Context.IsSeekable}"`
`    Maximum="{Binding Context.Duration.TotalSeconds}"`
`    Minimum="0"`
`    Value="{Binding Context.Position.Seconds}" />`

the slider resets to 0 and progresses until it hits 60 seconds, then it resets back to 0 again.

The TextBlock code showing the StringFormat "Context.Position" is working properly; it's counting past 60 seconds, adding 1 minute to the formatted "Context.Position".

**Comment by homov** [comment]
You have to change

Context.Position.Seconds
to
Context.Position.**TotalSeconds**

Context.Position is Timepan. Please read the difference between:

Timspan.Seconds
https://learn.microsoft.com/en-us/dotnet/api/system.timespan.seconds?view=net-7.0

AND

Teamspan.TotalSeconds
https://learn.microsoft.com/en-us/dotnet/api/system.timespan.totalseconds?view=net-7.0

**Comment by pvogt** [comment]
I figured it out. Instead of "Context.Position.Seconds", I should be using "Context.Position.TotalSeconds".

Thank you for finding a different way to use MPV in a project.
Using your 'OpenGlVideoView' solves the Airspace issue with MPV that similar projects have where components can't be placed over the MPV video.
