### ISSUE TITLE
How to achieve a circular playback video?

### ISSUE THREAD

**Issue by chenzanyu** [homov/LibMpv#8]
PlaylistMode.none: End playback once end of the playlist is reached.
PlaylistMode.single: Indefinitely loop over the currently playing file in the playlist.
PlaylistMode.loop: Loop over the playlist & restart it from beginning once end is reached.

I just came across this repo. Is this functionality already encapsulated, or do I need to implement it myself?

**Comment by homov** [comment]
This library is simply a wrapper over the libmpv library.
You need to read the libmpv documentation to understand how to achieve the desired result.

Please see the documentation about the commands, properties and options:
https://mpv.io/manual/master/#list-of-input-commands
https://mpv.io/manual/master/#properties
https://mpv.io/manual/master/#options

For example:
to load playlist use  **loadlist** command
to loop playlist use **loop-playlist** option
...
